"""Submit URLs to IndexNow for instant indexing by Bing, DuckDuckGo, Yandex, etc.

IndexNow notifies participating search engines the moment content changes, instead
of waiting for a crawl. Bing powers Copilot + ChatGPT search, so this is the fastest
path to getting new posts into the AI-citation index.

The key (589c30d54f9f3681d19765a4f3dd71b6) is intentionally public: it is verified by
fetching https://avinashsangle.com/<key>.txt, so it is committed in public/, not a secret.

URLs must be canonical (no trailing slash). The site runs Next.js with the default
trailingSlash: false, so "/blog/<slug>/" 308-redirects to "/blog/<slug>", and Bing
rejects redirects with "The inspected URL is a redirect and cannot be indexed."
--all reads the live sitemap (generated by src/app/sitemap.ts), which is the same
document search engines fetch, so it is canonical by construction.

Usage:
    python3 scripts/submit_indexnow.py <url> [<url> ...]   # submit specific URLs
    python3 scripts/submit_indexnow.py --all               # submit every URL in the live sitemap
    python3 scripts/submit_indexnow.py --all --dry-run     # show what would be sent

Examples:
    python3 scripts/submit_indexnow.py https://avinashsangle.com/blog/claude-md-guide
    python3 scripts/submit_indexnow.py --all
"""

import argparse
import json
import re
import sys
import urllib.error
import urllib.request

KEY = "589c30d54f9f3681d19765a4f3dd71b6"
HOST = "avinashsangle.com"
KEY_LOCATION = f"https://{HOST}/{KEY}.txt"
ENDPOINT = "https://api.indexnow.org/indexnow"
SITEMAP_URL = f"https://{HOST}/sitemap.xml"
ORIGIN = f"https://{HOST}"


def urls_from_sitemap() -> list:
    # Read the LIVE sitemap (src/app/sitemap.ts renders /sitemap.xml) rather than a file
    # on disk. A checked-in copy silently goes stale and takes IndexNow down with it.
    # Regex extraction avoids an XML parser (no XXE surface).
    try:
        with urllib.request.urlopen(SITEMAP_URL, timeout=30) as resp:
            body = resp.read().decode("utf-8", "replace")
    except (urllib.error.URLError, urllib.error.HTTPError) as exc:
        sys.exit(f"Could not fetch {SITEMAP_URL}: {exc}")
    urls = [m.strip() for m in re.findall(r"<loc>(.*?)</loc>", body, re.S)]
    if not urls:
        sys.exit(f"No <loc> entries found in {SITEMAP_URL}")
    return urls


def reject_redirects(urls: list) -> None:
    # A trailing slash on any path is a 308 to the canonical URL; submitting it wastes
    # the ping and Bing reports it as an un-indexable redirect. The bare origin is fine.
    bad = [u for u in urls if u.endswith("/") and u.rstrip("/") != ORIGIN]
    if bad:
        sys.exit(
            "Refusing: these URLs 308-redirect to their canonical form (drop the "
            f"trailing slash):\n  " + "\n  ".join(bad)
        )


def submit(urls: list, dry_run: bool) -> None:
    if not urls:
        sys.exit("No URLs to submit.")
    bad = [u for u in urls if not u.startswith(f"https://{HOST}")]
    if bad:
        sys.exit(f"Refusing: these URLs are not on {HOST}: {bad}")
    reject_redirects(urls)

    payload = {"host": HOST, "key": KEY, "keyLocation": KEY_LOCATION, "urlList": urls}

    if dry_run:
        print(f"DRY RUN — would POST {len(urls)} URL(s) to {ENDPOINT}:")
        for u in urls:
            print(f"  {u}")
        return

    req = urllib.request.Request(
        ENDPOINT,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            code = resp.status
    except urllib.error.HTTPError as exc:
        # IndexNow uses status codes as the response; 200/202 are success.
        code = exc.code
        if code not in (200, 202):
            body = exc.read().decode("utf-8", "replace")[:300]
            sys.exit(f"IndexNow rejected submission ({code}): {body}")

    meaning = {200: "OK", 202: "Accepted (key validation pending)"}.get(code, str(code))
    print(f"Submitted {len(urls)} URL(s) — IndexNow returned {code} ({meaning}).")
    for u in urls:
        print(f"  {u}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Submit URLs to IndexNow (Bing/DuckDuckGo/Yandex).")
    parser.add_argument("urls", nargs="*", help="Specific URLs to submit")
    parser.add_argument("--all", action="store_true", help="Submit every URL in the live sitemap")
    parser.add_argument("--dry-run", action="store_true", help="Print URLs without submitting")
    args = parser.parse_args()

    urls = urls_from_sitemap() if args.all else args.urls
    if not urls:
        parser.error("Provide URLs or use --all")
    submit(urls, args.dry_run)


if __name__ == "__main__":
    main()
